name: Update Labels on Card Move

on:
  project_card:
    types:
      - moved

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Update Labels
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_BOARD_TOKEN }}
        run: node update-labels.js
